package com.supplychain;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public final class DashboardGenerator {

    private DashboardGenerator() {
    }

    public static void generate() throws IOException {
        List<String> carrierRows = Files.readAllLines(Path.of("data/carrier_summary.csv"));
        List<String> bottleneckRows = Files.readAllLines(Path.of("data/warehouse_bottlenecks.csv"));
        List<String> predictionRows = Files.readAllLines(Path.of("data/supply_chain_predictions.csv"));
        long highRiskCount = predictionRows.stream().skip(1)
                .filter(row -> row.endsWith(",High Risk"))
                .count();

        StringBuilder html = new StringBuilder("""
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <title>Supply Chain Analytics Dashboard</title>
                  <style>
                    body { font-family: Arial, sans-serif; margin: 2rem auto; max-width: 1100px; color: #17324d; background: #f4f7f9; }
                    header { background: #17324d; color: white; padding: 1.5rem 2rem; border-radius: 8px; }
                    .metrics { display: flex; gap: 1rem; margin: 1.5rem 0; flex-wrap: wrap; }
                    .metric { background: white; border-left: 5px solid #e07a3f; padding: 1rem 1.5rem; min-width: 180px; box-shadow: 0 2px 8px #17324d18; }
                    table { border-collapse: collapse; background: white; width: 100%; margin: 1rem 0 2rem; }
                    th, td { border-bottom: 1px solid #dbe3e8; padding: .7rem; text-align: left; }
                    th { background: #dceaf0; }
                  </style>
                </head>
                <body>
                  <header><h1>Supply Chain Analytics Dashboard</h1><p>Generated by the Java 17 analytics pipeline</p></header>
                """);
        html.append("<section class=\"metrics\"><div class=\"metric\"><strong>Shipments</strong><br>")
                .append(predictionRows.size() - 1).append("</div><div class=\"metric\"><strong>High-risk shipments</strong><br>")
                .append(highRiskCount).append("</div></section>");
        appendTable(html, "Carrier performance", carrierRows);
        appendTable(html, "Warehouse bottlenecks", bottleneckRows);
        html.append("</body></html>");
        Files.writeString(Path.of("data/dashboard.html"), html);
        System.out.println("Dashboard generated -> data/dashboard.html");
    }

    private static void appendTable(StringBuilder html, String title, List<String> rows) {
        html.append("<h2>").append(title).append("</h2><table>");
        for (int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
            html.append(rowIndex == 0 ? "<thead><tr>" : "<tr>");
            for (String cell : rows.get(rowIndex).split(",", -1)) {
                html.append(rowIndex == 0 ? "<th>" : "<td>").append(cell).append(rowIndex == 0 ? "</th>" : "</td>");
            }
            html.append(rowIndex == 0 ? "</tr></thead><tbody>" : "</tr>");
        }
        html.append("</tbody></table>");
    }
}
